config/routes.rb
Rails.application.routes.draw do

  post :incoming, to: 'incoming#create'

  resources :topics do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users

  resources :users, only: [:show]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
  validates :title,
            presence: true,
            uniqueness: { case_sensitive: false }

  before_save :title_to_downcase

  private

  def title_to_downcase
    self.title = title.downcase
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    @topic.user = current_user
    if @topic.save
      flash[:notice] = "Topic successfully created!"
      redirect_to topic_path(@topic)
    else
      flash[:alert] = "Topic was not created. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    @topic.assign_attributes(topic_params)
    if @topic.save
      flash[:notice] = "Topic successfully updated!"
      redirect_to topic_path(@topic)
    else
      flash[:alert] = "Topic not updated. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was successfully deleted."
      redirect_to topics_path
    else
      flash[:alert] = "Topic was NOT deleted. Please try again."
      render :show
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :user_id)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def random_class
    classes = [
      "bg-color-1",
      "bg-color-2",
      "bg-color-3",
      "bg-color-4",
      "bg-color-5",
      "bg-color-6",
      "bg-color-7",
      "bg-color-8",
      "bg-color-9",
      "bg-color-10"
    ]
    classes.sample
  end

end

app/views/topics/edit.html.erb
<h1>
  <span class="gray-light">Edit Topic</span>
  <br />
  <%= @topic.title %>
</h1>
<br />
<div class="row">
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>

app/views/topics/index.html.erb
<h1>Blocmarks Topics</h1>
<br />
<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to topic.title, topic_path(topic) %>
          <small>by <%= topic.user.user_name %></small>
        </h4>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter topic title' %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<div class="buttons">
  <% if policy(@topic).edit? %>
    <%= link_to "Edit", edit_topic_path(@topic), class: 'btn btn-primary', title: 'Click to modify this topic' %>
  <% end %>
  <% if policy(@topic).destroy? %>
    <%= link_to "Delete", @topic, method: :delete, class: 'btn btn-danger', title: 'Click to delete this topic',
                                        data: { confirm: "Are you sure you want to delete this Topic?" } %>
  <% end %>
</div>
<br />
<div class="row">
  <div class="col-md-8">
    <% @topic.bookmarks.each do |bookmark| %>
      <div class="media">
        <div class="media-body">
          <!-- CRUD -->
          <% if policy(bookmark).show? %>
            <small><%= link_to "Show", bookmark_path(bookmark.id) %></small>
          <% end %>

          <% if policy(bookmark).edit? %>
            | <small><%= link_to "Edit", edit_bookmark_path(bookmark) %></small> |
          <% end %>
          <% if policy(bookmark).destroy? %>
            <small><%= link_to "Delete", bookmark, method: :delete, data: { confirm: "Are you sure you want to delete this bookmark?" } %></small>
          <% end %>

          <p class="<%= random_class %>">
            <%= link_to  bookmark.url do %>
              <%= bookmark.description ? excerpt(bookmark.description, ' ', radius: 20) : bookmark.url %>
            <% end %>
          </p>

          <!-- Like/Unlike -->
          <% if current_user.liked?(bookmark) %>
            <% like = current_user.likes.where(bookmark_id: bookmark).take %>
            <%= link_to bookmark_like_path(bookmark, like), method: :delete, class: 'btn btn-danger', title: "Unlike this bookmark." do %>
              <i class="glyphicon glyphicon-star-empty"> </i>&nbsp;Unlike
            <% end %>
          <% else %>
            <%= link_to bookmark_likes_path(bookmark), method: :post, class: 'btn btn-primary', title: "Like this bookmark." do %>
              <i class="glyphicon glyphicon-star"> </i>&nbsp;Like
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-primary' %>
  </div>
</div>