config/routes.rb
Rails.application.routes.draw do

  post :incoming, to: 'incoming#create'

  resources :topics do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users

  resources :users, only: [:show]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :topics
  has_many :bookmarks
  has_many :likes
  has_many :liked_bookmarks, through: :likes, source: :bookmark

  def liked?(bookmark)
    bookmark.likes.where(user_id: id).any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @bookmarked_topics = @user.bookmarks.includes(:topic).group_by(&:topic)
    @liked_bookmarks = @user.liked_bookmarks.includes(:topic).group_by(&:topic)
  end
end

app/views/users/show.html.erb
<h1><%= @user.user_name %>'s Blocmarks</h1>
<div class="row my-page">
  <div class="col-md-4 my-bookmarks">
    <h2>My Bookmarks</h2>
      <% @bookmarked_topics.each do |topic, bookmarks| %>
        <h3><%= link_to topic.title, topic_path(topic) %></h3>
        <ul>
          <% bookmarks.each do |bookmark| %>
          <li>
            <% if bookmark.description != "" %>
              <%= link_to bookmark.description, bookmark.url %>
            <% else %>
              <%= link_to bookmark.url %>
            <% end %>
          </li>
          <p class="crud">
            <% if policy(bookmark).show? %>
              <small><%= link_to "Show", bookmark_path(bookmark) %></small>
            <% end %>
            <% if policy(bookmark).edit? %>
              <small><%= link_to "Edit", edit_bookmark_path(bookmark) %></small>
            <% end %>
            <% if policy(bookmark).destroy? %>
              <small><%= link_to "Delete", bookmark, method: :delete,  data: { confirm: "Are you sure you want to delete this bookmark?" } %></small>
            <% end %>
          </p>
          <% end %>
        </ul>
      <% end %>
  </div>
  <div class="col-md-1">
  </div>
  <div class="col-md-4 my-likes">
    <h2>My Likes</h2>
    <% @liked_bookmarks.each do |topic, liked_bookmarks| %>
      <h3><%= link_to topic.title, topic_path(topic) %></h3>
      <ul>
        <% liked_bookmarks.each do |bookmark| %>
        <% like = current_user.likes.where(bookmark_id: bookmark).take %>
        <%= link_to bookmark_like_path(bookmark, like), method: :delete, class: 'btn btn-danger btn-xs' do %>
          <i class="glyphicon glyphicon-star-empty">&nbsp; Unlike</i>
        <% end %>
          <li>
            <% if bookmark.description != "" %>
              <%= link_to bookmark.description, bookmark.url %>
            <% else %>
              <%= link_to bookmark.url %>
            <% end %>
          </li>
          <p class="crud">
            <% if policy(bookmark).show? %>
              <small><%= link_to "Show", bookmark_path(bookmark) %></small>
            <% end %>
            <% if policy(bookmark).edit? %>
              <small><%= link_to "Edit", edit_bookmark_path(bookmark) %></small>
            <% end %>
            <% if policy(bookmark).destroy? %>
              <small><%= link_to "Delete", bookmark, method: :delete,  data: { confirm: "Are you sure you want to delete this bookmark?" } %></small>
            <% end %>
          </p>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="col-md-1">
  </div>
  <div class="col-md-2 my-topics">
    <h2>My Topics</h2>
    <% @user.topics.each do |topic| %>
      <h3><%= topic.title  %></h3>
      <p class="crud">
        <% if policy(topic).show? %>
          <small><%= link_to "Show", topic_path(topic) %></small>
        <% end %>
        <% if policy(topic).edit? %>
          <small><%= link_to "Edit", edit_topic_path(topic) %></small>
        <% end %>
        <% if policy(topic).destroy? %>
          <small><%= link_to "Delete", topic, method: :delete,  data: { confirm: "Are you sure you want to delete this topic?" } %></small>
        <% end %>
      </p>
    <% end %>
  </div>
</div>