config/routes.rb
Rails.application.routes.draw do

  post :incoming, to: 'incoming#create'

  resources :topics do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users

  resources :users, only: [:show]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
	<ul class="nav nav-tabs">
		<li><%= link_to "Home", welcome_index_path %></li>
    <li><%= link_to "Topics", topics_path %></li>
    <li><%= link_to "About", welcome_about_path %></li>
    <div class="pull-right user-info">
      <% if user_signed_in? %>
        <strong><%= link_to current_user.user_name, user_path(current_user), title: "Go to your Blocmarks page." %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
        -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
	</ul>
	<% if flash[:notice] %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<p class="notice"><%= notice %></p>
		</div>
	<% elsif flash[:alert] %>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<p class="alert"><%= alert %></p>
		</div>
	<% end %>

  <%= yield %>

  </div>
</body>
</html>